### ISSUE TITLE
请问怎么新增svg或者iconfont类型图源

### ISSUE THREAD

**Issue by akon3585** [Jason-chen-coder/mxgraph-EasyEditor#23]

**Comment by Jason-chen-coder** [comment]
可以参考分组节点上的用法, mxgraph是支持节点内容使用html渲染的,
![image](https://user-images.githubusercontent.com/53551357/134842636-57ff38b0-4611-4b9c-9795-556f5bff3d06.png)
![image](https://user-images.githubusercontent.com/53551357/134842747-f4f2c003-0ab8-4fdd-b8e7-ca16d2e633fb.png)

**Comment by akon3585** [comment]
> 可以参考分组节点上的用法, mxgraph是支持节点内容使用html渲染的,
> ![image](https://user-images.githubusercontent.com/53551357/134842636-57ff38b0-4611-4b9c-9795-556f5bff3d06.png)
> ![image](https://user-images.githubusercontent.com/53551357/134842747-f4f2c003-0ab8-4fdd-b8e7-ca16d2e633fb.png)

感谢
